specVersion: 0.2.0
name: polkadot-governance
version: 0.0.4
description: >-
  This project can be use as a starting point for developing your SubQuery
  project
repository: 'https://github.com/subquery/subql-starter'
schema:
  file: ./schema.graphql
network:
  endpoint: 'wss://rpc.polkadot.io'
  genesisHash: '0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3'
dataSources:
  - kind: substrate/Runtime
    startBlock: 9342824
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleProposed
          kind: substrate/EventHandler
          filter:
            module: democracy
            method: Proposed
        - handler: handleTabled
          kind: substrate/EventHandler
          filter:
            module: democracy
            method: Tabled
        - handler: handleExternalTabled
          kind: substrate/EventHandler
          filter:
            module: democracy
            method: ExternalTabled
        - handler: handleStarted
          kind: substrate/EventHandler
          filter:
            module: democracy
            method: Started
        - handler: handlePassed
          kind: substrate/EventHandler
          filter:
            module: democracy
            method: Passed
        - handler: handleNotPassed
          kind: substrate/EventHandler
          filter:
            module: democracy
            method: NotPassed
        - handler: handleCancelled
          kind: substrate/EventHandler
          filter:
            module: democracy
            method: Cancelled
        - handler: handleExecuted
          kind: substrate/EventHandler
          filter:
            module: democracy
            method: Executed
        - handler: handleDelegated
          kind: substrate/EventHandler
          filter:
            module: democracy
            method: Delegated
        - handler: handleUndelegated
          kind: substrate/EventHandler
          filter:
            module: democracy
            method: Undelegated
        - handler: handleVetoed
          kind: substrate/EventHandler
          filter:
            module: democracy
            method: Vetoed
        - handler: handlePreimageNoted
          kind: substrate/EventHandler
          filter:
            module: democracy
            method: PreimageNoted
        - handler: handlePreimageUsed
          kind: substrate/EventHandler
          filter:
            module: democracy
            method: PreimageUsed
        - handler: handlePreimageInvalid
          kind: substrate/EventHandler
          filter:
            module: democracy
            method: PreimageInvalid
        - handler: handlePreimageMissing
          kind: substrate/EventHandler
          filter:
            module: democracy
            method: PreimageMissing
        - handler: handlePreimageReaped
          kind: substrate/EventHandler
          filter:
            module: democracy
            method: PreimageReaped
        - handler: handleBlacklisted
          kind: substrate/EventHandler
          filter:
            module: democracy
            method: Blacklisted
        - handler: handleVoted
          kind: substrate/EventHandler
          filter:
            module: democracy
            method: Voted
        - handler: handleSeconded
          kind: substrate/EventHandler
          filter:
            module: democracy
            method: Seconded
